  ---
functional:
  - Требование 1 
  - Требование 2 
  - Требование 3 
  - Требование 4 
  - Требование 5 
  - Требование 6 
  - Требование 7 
  - Требование 8   
non-functional:
  - Требование 9 Сайт должен быть доступен на различных устройствах
  - Требование 10 Сайт должен иметь мобильную версию
  - Требование 11 Сайт должен быть кроссбраузерным
  - Требование 12 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 13 Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Требование 14 Сайт должен быть нагрузоустойчивым
  - Требование 15 Сайт должен быть SPA-приложением
implicit:
  - Требование 16 
  - Требование 17 
  - Требование 18 
