  ---
functional:
  - Требование 1 Пользователь должен иметь возможность начать игру без регистрации и авторизации
  - Требование 2 Пользователь должен иметь возможность зарегистрироваться на сайте
  - Требование 3 Пользователь должен иметь возможность войти в игру с помощью email, Github или Discord
  - Требование 4 Пользователь должен иметь возможность выбрать уровень сложности игры
  - Требование 5 Пользователь должен иметь возможность выбрать тип игры с другим пользователем, с другом или с ботом
  - Требование 6 Пользователь должен иметь возможность выбрать длительность игры
  - Требование 7 Пользователь должен иметь возможность выбрать любую задачу или сыграть в случайную
  - Требование 8 Пользователь должен иметь возможность выбрать задачи с определенным тегом
  - Требование 9 Пользователь должен иметь возможность пригласить на бой другого игрока
  - Требование 10 Пользователь должен иметь возможность принять приглашение на бой от другого игрока
  - Требование 11 Пользователь должен иметь возможность писать сообщения в общем чате
  - Требование 12 Пользователь должен иметь возможность писать сообщения в чате игры с другим игроком
  - Требование 13 Пользователь должен иметь возможность выбора языка текста задачи
  - Требование 14 Пользователь должен иметь возможность выбора языка программирования до решения задач
  - Требование 15 Пользователь должен иметь возможность смены языка программирования во время решения задачи
  - Требование 16 Пользователь должен иметь возможность написать личное сообщение другому игроку
  - Требование 17 Пользователь должен иметь возможность сдаться во время игры
  - Требование 18 Пользователь должен иметь возможность зайти заново в игру, в которой он сдался и продолжить решение
  - Требование 19 Пользователь должен иметь возможность следить за игрой других пользователей онлайн
  - Требование 20 Пользователь должен иметь возможность закончить игру в случае проигрыша, дописать код, проверить правильность
  - Требование 21 Пользователь должен иметь возможность видеть код соперника во время игры
  - Требование 22 Пользователь должен иметь возможность посмотреть завершенную игру в записи
  - Требование 23 Пользователь должен иметь возможность повышать свой рейтинг, получая очки за выигранные игры
  - Требование 24 Пользователь должен иметь возможность
non-functional:
  - Требование 9 Сайт должен быть доступен на различных устройствах
  - Требование 10 Сайт должен иметь мобильную версию
  - Требование 11 Сайт должен быть кроссбраузерным и совместимым с последними версиями браузеров
  - Требование 12 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 13 Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Требование 14 Сайт должен быть нагрузоустойчивым
  - Требование 15 Сайт должен быть SPA-приложением
implicit:
  - Требование 16 Пользователь должен иметь возможность просматривать свой профиль
  - Требование 17 Пользователь должен иметь возможность редактировать свой профиль
  - Требование 18 Пользователь должен иметь возможность менять настройки звуковые в игре
  - Требование 18 Пользователь должен иметь возможность просматривать рейтинги игроков
  - Требование 18 Пользователь должен иметь возможность просматривать историю игр других игроков
  - Требование 18 Пользователь должен иметь возможность 
  - Требование 18 Пользователь должен иметь возможность
  - Требование 18 Пользователь должен иметь возможность
